FROM bioconductor/bioconductor_docker:RELEASE_3_18

LABEL maintainer="emmanueltan2000@gmail.com" \
      description="deltaTE: Detection of translationally regulated genes" \
      version="1.0.0"

RUN R -e "\
    options(Ncpus = parallel::detectCores()); \
    if(!require('BiocManager')) install.packages('BiocManager'); \
    BiocManager::install(c('DESeq2', 'apeglm'), ask=FALSE); \
    if(!require('ggplot2')) install.packages('ggplot2'); \
    " && rm -rf /tmp/downloaded_packages/

WORKDIR /app
COPY scripts/DTEG.R /app/
RUN chmod +x /app/DTEG.R

ENTRYPOINT ["Rscript", "/app/DTEG.R"]

docker run --rm \
  --platform=linux/amd64 \
  -v $(pwd)/examples/data:/data \
  -w /data \
  107laserfish/deltate:latest-lite ribo_counts.txt rna_counts.txt sample_info.txt 1


docker run --rm -it \
  --platform=linux/amd64 \
  -v $(pwd)/examples/data:/data \
  -w /data \
  --entrypoint bash \
  107laserfish/deltate:latest-lite