name: Build and Push Docker Image (Bioconductor)

on:
    # push:
        # branches: [ main ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile.fromBioconductor
        context: .
        push: true
        tags: |
            ${{ secrets.DOCKER_USERNAME }}/deltate-bioconductor:latest
        platforms: |
            linux/amd64