name: Test Bioconductor Image (manual)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image (Bioconductor)"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/deltate-bioconductor:latest
      EXAMPLES_DIR: ${{ github.workspace }}/examples/data
      OUTPUT_DIR: ${{ github.workspace }}/test-results

    steps:
      - name: Checkout repo (to get examples & scripts)
        uses: actions/checkout@v4

    #   - name: Ensure examples exist
    #     run: |
    #       if [ ! -d "$EXAMPLES_DIR" ]; then
    #         echo "'examples/' directory not found at repo root."
    #         exit 1
    #       fi
    #       ls -lah "$EXAMPLES_DIR"

      - name: Create output dir
        run: mkdir -p "$OUTPUT_DIR"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull image
        run: docker pull "$IMAGE_NAME"

      - name: Run container (ENTRYPOINT mode)
        run: |
          docker run --rm \
            -v "$EXAMPLES_DIR:/home/ruser/examples" \
            -v "$OUTPUT_DIR:/home/ruser/Results" \
            "$IMAGE_NAME" \
            /home/ruser/examples/ribo_counts.txt \
            /home/ruser/examples/rna_counts.txt \
            /home/ruser/examples/sample_info.txt \
            1

      - name: List results
        run: ls -lah "$OUTPUT_DIR" || true

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: bioc-image-test-results
          path: ${{ env.OUTPUT_DIR }}
          if-no-files-found: warn
